spring:
  datasource:
    url: jdbc:mysql://localhost:3306/personalblog?useUnicode=true&characterEncoding=utf8
    username: root
    password: 1509982360
    driver-class-name: com.mysql.cj.jdbc.Driver

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

logging:
  level:
    root: warn
    com.lyx: info
  file:
    path: log/blog.log

server:
  port: 8080
